### ISSUE TITLE
Support `layoutChanged` and `layoutAboutToBeChanged` signals

### ISSUE THREAD

**Issue by poul1x** [stlehmann/PyQt5-stubs#191] opened 2022-02-19 14:05 UTC
Please, support [layoutAboutToBeChanged()](http://doc.qt.io/qt-4.8/qabstractitemmodel.html#layoutAboutToBeChanged) and [layoutChanged()](http://doc.qt.io/qt-4.8/qabstractitemmodel.html#layoutChanged) signals. As you see, they are recognized as functions.

![image](https://user-images.githubusercontent.com/31695750/154804008-bac797cb-0cb7-4d33-8ca9-3109010b0e39.png)

<img src="https://user-images.githubusercontent.com/31695750/154803897-ea2b83fe-624e-4ed6-a73d-f3bc22722d17.png" height="400" />

**PyQt5-stubs version**: 5.15.2.0

**Comment by bluebird75** [comment] 2022-02-22 19:29
which version of pyqt5-stubs are you using ?

**Comment by poul1x** [comment] 2022-02-22 23:15
`PyQt5-stubs==5.15.2.0`

**Comment by bluebird75** [comment] 2022-03-07 21:32
Hi,

Thanks for reporting this. Sorry for the delay.

The fix for these two signals (and many others) are already in the codebase, but it has not yet been released.

You can install the git version with : 

`pip install git+https://github.com/python-qt-tools/PyQt5-stubs@master
`

I just checked it with your example, it works fine and fixes your problem.

Now, let's head up to a release. @altendky ?

**Comment by bluebird75** [comment] 2022-04-23 09:55
I have just released PyQt5-stubs 5.15.6.0 which includes a fix for this issue. Please upgrade and reopen the issue in case the problem is still present. And if you find additional issues, don't hesitate to report them.

**Closed as completed by bluebird75** 2022-04-23 09:55 UTC
